let g:coc_global_extensions = [
\  'coc-css',
\  'coc-cssmodules',
\  'coc-eslint',
\  'coc-elixir',
\  'coc-html',
\  'coc-jest',
\  'coc-json',
\  'coc-git',
\  'coc-markdownlint',
\  'coc-prettier',
\  'coc-styled-components',
\  'coc-sql',
\  'coc-svg',
\  'coc-tsserver',
\  'coc-solargraph',
\  'coc-pyright',
\  'coc-go',
\  'coc-snippets',
\  'coc-yaml'
\]
