#!/bin/sh
if [[ "$OSTYPE" != "darwin"* ]]
then
  echo "Running brew not on mac? Y U DO DIS?"
  return 1
fi

if which pyenv > /dev/null 2>&1; then
  # assumes default location of brew in `/usr/local/bin/brew`
  /usr/bin/env PATH="${PATH//$(pyenv root)\/shims:/}" /usr/local/bin/brew "$@"
else
  /usr/local/bin/brew "$@"
fi
