#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  if ps aux | grep "IntelliJ IDEA.app" | grep -v grep &> /dev/null; then
    open -a IntelliJ\ IDEA $@
  else
    idea $@
  fi
else
  echo "Not implemented use idea instead"
fi
