#!/bin/bash

### Homebrew
if which brew > /dev/null 2>&1 && brew --version > /dev/null 2>&1
then
  brew update && brew upgrade && brew cask upgrade && brew cleanup && brew doctor
fi

### apt get
if which apt > /dev/null 2>&1 && apt --version > /dev/null 2>&1
then
  sudo apt update
  sudo apt upgrade
fi

### Pyenv
if [[ -s "$HOME/.pyenv/plugins/pyenv-update/bin/pyenv-update" ]] &&
  which pyenv > /dev/null 2>&1
then
  pyenv update
fi

### ZimFramework
if [[ -d "$HOME/.zim" ]]
then
  (cd "$HOME/.zim" &&
    git remote update -p &&
    git merge --ff-only @{u} &&
    git submodule update --init --recursive)
fi
